export const LIMITS = {
  questionsPremium: 100,
  questionsFree: 20,
  hiddenFree: 5,
  questionText: 300,
  answerText: 500,
  penaltyLabel: 40,
  penaltyDescription: 200,
  customPenalties: 6,
  activeGames: 10,
  title: 60,
  guestName: 40,
  strikeBackMax: 2,
  projectionRounds: 100,
  snapshotsKeep: 20,
  snapshotMinIntervalSec: 30,
  retentionDays: 90,
  retentionWarnDays: 83,
  fixupAfterFinishHours: 24,
} as const;
